services:
  # Acme.sh untuk generate SSL certificate dengan DNS challenge
  acme:
    image: neilpang/acme.sh
    container_name: acme-mailserver
    command: daemon
    environment:
      - CF_Token=QBoCL3RAxwhWEuEAQ-C5lNVFUTCIViQbkcT6cdsO
    volumes:
      - acme-data:/acme.sh
      - mailserver-certs:/etc/letsencrypt
    restart: always

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.madev.cloud
    env_file: .env
    depends_on:
      - acme
    ports:
      - "25:25"    # SMTP
      - "143:143"  # IMAP4
      - "465:465"  # ESMTP (TLS)
      - "587:587"  # ESMTP (STARTTLS)
      - "993:993"  # IMAP4 (TLS)
    volumes:
      - mailserver-data:/var/mail/
      - mailserver-state:/var/mail-state/
      - mailserver-logs:/var/log/mail/
      - mailserver-config:/tmp/docker-mailserver/
      - mailserver-certs:/etc/letsencrypt:ro
      - /etc/localtime:/etc/localtime:ro
    restart: no
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --ipv4 --tcp | grep --silent ':smtp' || exit 1"
      timeout: 3s
      retries: 0

volumes:
  acme-data:
    driver: local
  mailserver-data:
    driver: local
  mailserver-state:
    driver: local
  mailserver-logs:
    driver: local
  mailserver-config:
    driver: local
  mailserver-certs:
    driver: local
